### ISSUE TITLE
Penalty function for nonlinear inequality constraints in Mystic are evaluated outside of bounds

### ISSUE THREAD

**Issue by degloff** [uqfoundation/mystic#153] opened 2021-11-12 07:49 UTC
I have a question related to the proper usage of the penalty function in mystic and just created a question on 
[StackOverflow](https://stackoverflow.com/questions/69938776/penalty-function-for-nonlinear-inequality-constraints-in-mystic-are-evaluated-ou).

Would be nice to understand better how to use it or fix it.

**Comment by mmckerns** [comment] 2021-11-12 15:19
Oddly enough, I've believe I've just "fixed" this issue earlier this week, and am working out whether or not it's better to change the default settings... and since you've preempted my ticket, I'll work within your ticket instead of creating a duplicate. I'll refer here on commits (unless we discover this is a separate issue).

While it's expected that penalty expressions (i.e. soft constraints) may be violated (and thus adding some penalty cost to the solution), the bounds and the "hard" constraints should not be violated.  Bounds are enforced by `SetStrictRanges` and constraints enforce themselves.  They are currently effectively implemented like this: `cost(constraints(penalty(bounds(x))))` where `bounds` will clip `x` if it's outside the set bounds, and `constraints` will ensure `x` satisfies the constraints.  The issue is that constraints don't ensure that the bounds are satisfied unless you explicitly add the bounds to the constraints, as done here:
https://stackoverflow.com/a/69885831/2379433

If the bounds are explicitly given in the constraints, then they will not be violated. I've added a new setting to automatically add the bounds to the constraints -- however, to do this generally, it's done at a later coupled optimization step than it is if one would add the bounds explicitly as I have in the link above (...essentially, leveraging the `sympy` solver instead of a later stage `mystic` solver).  Hence, as it can slow down the optimization in the general case, I'm considering not turning on this setting by default when `SetStrictRanges` is requested.  I'll get the commit in to the main branch once I figure out the best interface for it (i.e. what flags and/or methods should be called, and what the defaults should be).

If this isn't essentially what you are experiencing, then let me know, and I'll separate the threads.

**Comment by mmckerns** [comment] 2021-11-12 22:16
Also, as a point of clarification... a `penalty` provides "soft" constraints -- meaning, the constraints defined in `penalty` may be violated.  When they are violated, they add a penalty to the cost, with the intent of driving the solver away from `x` that violate the penalty constraints.

Hard constraints are imposed with the `constraints` keyword argument.

**Comment by mmckerns** [comment] 2021-11-12 22:28
Ah, I think I see what you mean.
Sorry your example wasn't too clear what the issue was, as you didn't show what was happening.  You are seeing an error because `q` needs to be restricted to positive values, and it apparently isn't (as seen here from `fmin_powell`):
```
    return 1.0 / (1 + c*sqrt(q))
ValueError: math domain error
```
This isn't exactly what I thought you were asking, but I think it can be handled by the same essential solution.  I'll work with your example...

**Comment by degloff** [comment] 2021-11-13 03:17
Yes sorry, that is exactly the problem. One solution is to modify the constraints and return a prohibitively large value in that case but it might be leading to other problems.

**Comment by degloff** [comment] 2021-11-13 03:17
> Also, as a point of clarification... a `penalty` provides "soft" constraints -- meaning, the constraints defined in `penalty` may be violated. When they are violated, they add a penalty to the cost, with the intent of driving the solver away from `x` that violate the penalty constraints.
> 
> Hard constraints are imposed with the `constraints` keyword argument.

Ah that is a good point, but because the constraints are nonlinear, I was not sure if that is going to work as well.

**Comment by mmckerns** [comment] 2021-11-13 13:20
Nonlinear constraints are not a problem.  Tight constraints are a bit difficult, but nonlinear is fine.  And when you are setting `k` at a huge value, you are essentially making the penalty function into a cliff... when a gradient works better, generally, to direct the solution toward a valid one.  A combination of `constraints` and `penalty` is usually pretty effective.

**Comment by mmckerns** [comment] 2021-11-13 15:44
I'll reply on SO as well, but like I said initially, the default is to clip on bounds violations, and not to restrict the range with penalties (soft constraints).  If you want to impose hard constraints, then you need to use the `constraints` keyword arg, as below.
```
import mystic.symbolic as ms
from mystic.constraints import and_
bounds = '''
x0 >= 0
x0 <= 50
x1 >= 0
x1 <= 300
'''
eqn = ms.simplify(bounds, all=True)
cons = ms.generate_constraint(ms.generate_solvers(eqn), join=and_)

mon = VerboseMonitor(10)
bounds=[(0, 50), (0, 300)]
result = fmin_powell(objective, x0=[15, 150], bounds=bounds, penalty=penalty,
                     npop=10, gtol=200, disp=False, full_output=True,
                     constraints=cons, itermon=mon, maxiter=500)
```

The above imposes the bounds with a hard constraint.  I'm in the finishing stages of adding this as a automatic option (as mentioned in my first comment).

**Comment by mmckerns** [comment] 2021-11-13 15:44
I'm going to close this, but open it if you feel it's not resolved.

**Closed by mmckerns** 2021-11-13 15:44 UTC
Labels: question
