### ISSUE TITLE
unqualified exec is not allowed in function '_load'

### ISSUE THREAD

**Issue by RoyiJZ** [uqfoundation/mystic#85] opened 2016-10-25 12:12 UTC
File "/home/royiz/workspace/TempPythonModules/mystic-master/mystic/monitors.py", line 496
    exec(string, globals()) #FIXME: unsafe, potential name conflict
SyntaxError: unqualified exec is not allowed in function '_load' it contains a nested function with free variables

**Comment by mmckerns** [comment] 2016-11-30 14:22
Hmm, I can't reproduce this error… however, I do know something that should fix it.  Can you test it?  I can't tell if you are on Windows or not, as I didn't test this change on Windows.

**Comment by mmckerns** [comment] 2016-11-30 14:23
fixed (possibly) in 76a3df60ca6fa070f2b26febd03350a2ff87ff27.  Again, I can't test it, as I'm not seeing this error.

**Comment by mmckerns** [comment] 2016-11-30 16:10
I have independent confirmation that the above was failing on Windows, and now works.  So, I'm closing this. @RoyiJZ, please reopen if it doesn't work for you.

**Closed by mmckerns** 2016-11-30 16:10 UTC
Labels: bug
