### ISSUE TITLE
simplify fails on equation with power for versions > 0.3.3

### ISSUE THREAD

**Issue by nelsoncsc** [uqfoundation/mystic#132] opened 2020-10-25 21:20 UTC
I have the following problem with mystic. The script below works in the version 0.3.3, but not in more recent versions and the script gets stuck.

```
M = 10
equations = '(1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 0.00390625'

bounds = [(0.0, M), (0.0, M)]
xs = [19.0, 19.0]
ys = 380.0

from mystic.symbolic import generate_constraint, generate_solvers, simplify
from mystic.symbolic import generate_penalty, generate_conditions


a = "({}+2**-{})".format(x_max,M)
b = "({}*2**-{})".format(abs(c0), M)
err_y = "{}*2**(-x0)+2**(-x1)+{} <= {}".format(a,b, acc_y)
equations = """{}""".format(err_y)

cf = generate_constraint(generate_solvers(simplify(equations)))
pf = generate_penalty(generate_conditions(equations), k=1e12)

from mystic.solvers import diffev2
from mystic.monitors import VerboseMonitor

mon = VerboseMonitor(10)
result = diffev2(objective, x0=[19.0, 19.0], bounds=bounds, constraints=cf, penalty=pf, npop=500, gtol=2000, disp=False, full_output=True, itermon=mon)
```

**Comment by mmckerns** [comment] 2020-10-25 23:16
With debugging turned on:
```
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1.0009765625*2**x1/(0.9994404296875*2**x1 - 1.0))/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
```
So there's definitely a problem somewhere -- `_0` should be `x0`, and `symsol` should be defined.

**Comment by mmckerns** [comment] 2020-10-25 23:20
```
^C^CTraceback (most recent call last):
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 698, in solve
    target=target, **kwds)
  File "<string>", line 157, in _solve_single
  File "<string>", line 4, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1096, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1870, in _solve_system
    soln = _solve(eq2, s, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1686, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 2693, in _tsolve
    if expand(lhs.base**n - rhs**d) == 0:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 212, in __pow__
    return self._pow(other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 251, in _func
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 127, in binary_op_wrapper
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 208, in _pow
    return Pow(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/power.py", line 317, in __new__
    obj = b._eval_power(e)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/numbers.py", line 2352, in _eval_power
    result = Integer(x**abs(expt.p))
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minibit.py", line 60, in <module>
    cf = ms.generate_constraint(ms.generate_solvers(simplify(equations)))
  File "minibit.py", line 38, in <lambda>
    simplify = lambda *args: ms.simplify(*args, **kwds)
  File "<string>", line 121, in simplify
  File "<string>", line 46, in _simplify
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/symbolic.py", line 333, in _solve_zeros
    eqn_ = solve(_eqn, target=variables, variables=x)
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 712, in solve
    target=target, **kwds)
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 870, in _solve_nonlinear
    invertedstring = _solve_single(eqn, variables=varname, target=_target, warn=warn, locals=locals, **kwarg)
  File "<string>", line 157, in _solve_single
  File "<string>", line 4, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1096, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1870, in _solve_system
    soln = _solve(eq2, s, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1686, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 2693, in _tsolve
    if expand(lhs.base**n - rhs**d) == 0:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 212, in __pow__
    return self._pow(other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 251, in _func
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 127, in binary_op_wrapper
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 208, in _pow
    return Pow(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/power.py", line 317, in __new__
    obj = b._eval_power(e)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/numbers.py", line 2352, in _eval_power
    result = Integer(x**abs(expt.p))
KeyboardInterrupt
```

**Comment by mmckerns** [comment] 2020-10-25 23:24
Debug, with `rational=True` produces: 
```
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
in: (1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1
out: x0 <= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)
zero: ['x1 != log(1024000/1023427)/log(2)', 'log(2) != 0']
```
Which means it doesn't "get stuck", but it still encounters the cause of the bug.

**Comment by mmckerns** [comment] 2020-10-25 23:31
Debug,  with `implicit=True` produces: 
```
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

Warning: target variable is not valid
{}
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x1], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x1: soln[-1][-1]} if soln else ""

Warning: target variable is not valid
{}
Warning: target variable is not valid
Warning: target variable is not valid
{'dependent': [], 'independent': [], 'unconstrained': ['x0', 'x1']}
in: (1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1
out: 
zero: []
Traceback (most recent call last):
  File "minibit.py", line 60, in <module>
    cf = ms.generate_constraint(ms.generate_solvers(simplify(equations)))
  File "minibit.py", line 38, in <lambda>
    simplify = lambda *args: ms.simplify(*args, **kwds)
  File "<string>", line 121, in simplify
  File "<string>", line 94, in _simplify
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/symbolic.py", line 379, in equals
    after, before = eval(after,{},locals_), eval(before,{},locals_)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

which looks like a syntax error, probably formed by a bad variable name or equation parsing or something like that...

**Comment by mmckerns** [comment] 2020-10-27 19:05
Simplifying the test code...
```
>>> equations = '(1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1'
>>> import mystic.symbolic as ms
>>> kwds = dict(warn=True, verbose=True, check=True)
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1.0009765625*2**x1/(0.9994404296875*2**x1 - 1.0))/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
^C^CTraceback (most recent call last):
    ...
```

**Comment by mmckerns** [comment] 2020-10-27 19:05
```
>>> equations = '(1 + 2**(-10)) * 2**(-x0) + 2**(-x1) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1 + 2**(-10)) * 2**(-x0) + 2**(-x1) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1.0009765625*2**x1/(2**x1 - 1))/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
in: (1 + 2**(-10)) * 2**(-x0) + 2**(-x1) <= 1
out: x0 <= log(1.0009765625*2**x1/(2**x1 - 1))/log(2)
zero: ['x1 != 0', 'log(2) != 0']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in simplify
  File "<string>", line 93, in _simplify
  File "<string>", line 77, in _testvals
  File "<string>", line 1
SyntaxError: can't assign to function call
```

**Comment by mmckerns** [comment] 2020-10-27 19:07
```
>>> equations = '2**(x0) + 2**(x1) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq(2**(x0) + 2**(x1) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1 - 2**x1)/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
in: 2**(x0) + 2**(x1) <= 1
out: x0 <= log(1 - 2**x1)/log(2)
zero: ['log(2) != 0']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in simplify
  File "<string>", line 93, in _simplify
  File "<string>", line 77, in _testvals
  File "<string>", line 1
SyntaxError: can't assign to function call
```

**Comment by mmckerns** [comment] 2020-10-27 19:09
```
>>> equations = '2**(x0) + 2 <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq(2**(x0) + 2 , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: I*pi/log(2)}
Warning: target variable is not valid
Warning: target variable is not valid
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 723, in solve
    if not soln: raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in simplify
  File "<string>", line 45, in _simplify
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/symbolic.py", line 333, in _solve_zeros
    eqn_ = solve(_eqn, target=variables, variables=x)
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 726, in solve
    target=target, **kwds)
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/_symbolic.py", line 890, in _solve_nonlinear
    _target = usedvars[i%len(usedvars)] #XXX: ...to make it len of neqns
ZeroDivisionError: integer division or modulo by zero
```

**Comment by mmckerns** [comment] 2020-10-27 19:10
```
>>> equations = '1**(x0) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq(1**(x0) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

Warning: target variable is not valid
{}
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq(1**(x0) , 1)
_xlist = (x0,)
_elist = [symsol([eq1], [i], **symsol_kwds) for i in _xlist]
_elist = [i if isinstance(i, dict) else {j:i[-1][-1]} for j,i in zip(_xlist,_elist) if i]
soln = dict()
[soln.update(i) for i in _elist if i]

Warning: name 'symsol' is not defined
{}
Warning: target variable is not valid
Warning: target variable is not valid
{'dependent': [], 'independent': [], 'unconstrained': ['x0']}
in: 1**(x0) <= 1
out: 
zero: []
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in simplify
  File "<string>", line 93, in _simplify
  File "/Users/mmckerns/lib/python3.6/site-packages/mystic-0.3.7.dev0-py3.6.egg/mystic/symbolic.py", line 379, in equals
    after, before = eval(after,{},locals_), eval(before,{},locals_)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by mmckerns** [comment] 2020-10-27 19:11
```
>>> equations = '2**(x0) <= 1 - 2**(x1)'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq(2**(x0) , 1 - 2**(x1))
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1 - 2**x1)/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
in: 2**(x0) <= 1 - 2**(x1)
out: x0 <= log(1 - 2**x1)/log(2)
zero: ['log(2) != 0']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in simplify
  File "<string>", line 93, in _simplify
  File "<string>", line 77, in _testvals
  File "<string>", line 1
SyntaxError: can't assign to function call
```

**Comment by mmckerns** [comment] 2020-10-27 19:11
```
>>> equations = '2**(x0) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq(2**(x0) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: 0}
in: 2**(x0) <= 1
out: x0 <= 0
zero: []
#: x0 <= 0
```
success

**Comment by mmckerns** [comment] 2020-10-27 20:17
```
>>> equations = '(1 + 2**(-10)) * 2**(-x0) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq((1 + 2**(-10)) * 2**(-x0) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

^C^CTraceback (most recent call last):
    ...
```

**Comment by mmckerns** [comment] 2020-10-27 20:17
```
>>> equations = '2**(-10) * 2**(-x0) <= 1'
>>> eqn = ms.simplify(equations, **kwds)
x0=Symbol('x0')
rand = Symbol('rand')
eq1= Eq(2**(-10) * 2**(-x0) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: -10}
in: 2**(-10) * 2**(-x0) <= 1
out: x0 <= -10
zero: []
#: x0 >= -10
```
Interesting...

**Comment by mmckerns** [comment] 2020-10-27 22:19
Here's the problem.  As I expected, `sympy` is failing to solve the equations. The reason that `0.3.3` worked, and newer versions have not, is that the default in `0.3.3` was `rational=True`... while in newer versions, it's `rational=False`. 
```
>>> from sympy import Symbol, Eq
>>> from sympy import solve as symsol
>>> x0=Symbol('x0')
>>> rand = Symbol('rand')
>>> eq1= Eq((1 + 2**(-10)) * 2**(-x0) , 1)
>>> soln = symsol([eq1], [x0], warn=True, check=True, implicit=False, manual=False, simplify=False, rational=True) 
>>> soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""
>>> soln
{x0: -10 + log(1025)/log(2)}
>>> 
>>> soln = symsol([eq1], [x0], warn=True, check=True, implicit=False, manual=False, simplify=False, rational=False)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1096, in solve
    solution = _solve_system(f, symbols, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1870, in _solve_system
    soln = _solve(eq2, s, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 1686, in _solve
    soln = _tsolve(f_num, symbol, **flags)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/solvers/solvers.py", line 2693, in _tsolve
    if expand(lhs.base**n - rhs**d) == 0:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 212, in __pow__
    return self._pow(other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 251, in _func
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/decorators.py", line 127, in binary_op_wrapper
    return func(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/expr.py", line 208, in _pow
    return Pow(self, other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/power.py", line 317, in __new__
    obj = b._eval_power(e)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sympy/core/numbers.py", line 2352, in _eval_power
    result = Integer(x**abs(expt.p))
KeyboardInterrupt
```

So, as a workaround, you can solve/simplify with `rational=False`.

**Comment by mmckerns** [comment] 2020-10-27 22:32
For `0.3.3`:
```
>>> equations = '(1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1'
>>> import mystic.symbolic as ms
>>> from mystic._symbolic033 import solve as solve033
>>> ms.solve = solve033
>>> kwds = dict(warn=True, verbose=True, rational=True)
>>> ms.simplify(equations, **kwds)
in: (1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1
out: x0 <= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))
zero: ['x1 != 0.000807515266734106']
#: ('x0 >= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))\nx1 > 0.000807515266734106', 'x0 >= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))\nx1 < 0.000807515266734106')
x0 >= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))
x1 > 0.000807515266734106
```

**Comment by mmckerns** [comment] 2020-10-27 22:43
For newer:
```
>>> equations = '(1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1'
>>> import mystic.symbolic as ms
>>> kwds = dict(warn=True, verbose=True, rational=True)
>>> ms.simplify(equations, **kwds)
x0=Symbol('x0')
x1=Symbol('x1')
rand = Symbol('rand')
eq1= Eq((1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) , 1)
soln = symsol([eq1], [x0], **symsol_kwds)
soln = soln if isinstance(soln, dict) else {x0: soln[-1][-1]} if soln else ""

{x0: log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)}
Warning: target variable is not valid
Warning: name 'symsol' is not defined
Warning: name '_0' is not defined
Warning: name '_0' is not defined
in: (1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1
out: x0 <= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)
zero: ['log(2) != 0', 'x1 != log(1024000/1023427)/log(2)']
Traceback (most recent call last):
  File "exponent.py", line 26, in <module>
    eqn = ms.simplify(equations, **kwds)
  File "<string>", line 120, in simplify
  File "<string>", line 93, in _simplify
  File "<string>", line 77, in _testvals
  File "<string>", line 1
SyntaxError: can't assign to function call
```

So, there's still an issue -- the `SyntaxError` that I was seeing in several of the above cases ... something that is also impacted by the `rational` setting.

Note that:
```
out: x0 <= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)
zero: ['log(2) != 0', 'x1 != log(1024000/1023427)/log(2)']
```
versus `0.3.3`:
```
out: x0 <= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))
zero: ['x1 != 0.000807515266734106']
```

Essentially, values like `log(2)` are not evaluated by default since `0.3.3`, unless `rational=False`.

I think this is fine... however, the SyntaxError is thrown because `log(2) != 0` is identified as a "zero".  It needs to be popped from the list of zeros to avoid.  Then everything should work fine when `rational=True`.

**Comment by mmckerns** [comment] 2020-10-27 22:45
Nice, so that's two bugs for the price of one.  The misidentification of the "zero" bug in `mystic`, and the bug in `sympy.solve` for exponentials with `rational=False`.

**Comment by mmckerns** [comment] 2020-10-27 23:24
Indeed:
```
>>> equation = 'x0 <= 1.44269504088896*log(1025000.0*2.0**x1/(1023427.0*2.0**x1 - 1024000.0))'
>>> import mystic.symbolic as ms
>>> from mystic._symbolic033 import solve as solve033
>>> ms.solve = solve033
>>> eqn = ms._solve_zeros(equation, ms.get_variables(equation, 'x'))
['x1 = 0.000807515266734106']
```
while:
```equation = 'x0 <= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)'```
produces:
```['log(2) = 0', 'x1 = (-log(1023427) + log(1024000))/log(2)']```

and with the newer versions (i.e. don't monkey-patch solve), the results are similar:
```
Warning: target variable is not valid
['x1 = 0.000807515266734207']
```
and
```
Warning: target variable is not valid
Warning: target variable is not valid
Warning: target variable is not valid
['log(2) = 0', 'x1 = log(1024000/1023427)/log(2)']
```

**Comment by mmckerns** [comment] 2020-10-28 00:18
added patch b96905466b0c06dd379c968a23e4c867c609a353

**Comment by mmckerns** [comment] 2020-10-28 00:25
```
>>> equation = 'x0 <= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)'
>>> import mystic.symbolic as ms
>>> vars = ms.get_variables(equation, 'x')
>>> ms._solve_zeros(equation, vars)
['x1 = log(1024000/1023427)/log(2)']
```
and
```
>>> equations = '(1+2**-10)*2**(-x0)+2**(-x1)+(0.573*2**-10) <= 1'
>>> import mystic.symbolic as ms
>>> ms.simplify(equations, warn=True, verbose=False, rational=True)
x0 >= log(1025000*2**x1/(1023427*2**x1 - 1024000))/log(2)
x1 < log(1024000/1023427)/log(2)
```

So, it looks like, with the workaround for the `sympy` bug (i.e. `rational=True`), then  `simplify` is working as expected.  Seems to throw some warnings... but otherwise is fine.

**Comment by mmckerns** [comment] 2020-10-28 00:27
@nelsoncsc: your original code now seems to run (with `rational=True`).  Please close this if it looks like it does what you expect.

**Closed** 2020-10-28 11:01 UTC
Labels: bug
