### ISSUE TITLE
pip installation errors

### ISSUE THREAD

**Issue by DBvdHeijden** [uqfoundation/mystic#170] opened 2022-04-19 13:30 UTC
Hi all!

When trying to install (either through pip or conda) I get an error with the numpy package (Failed building wheel for numpy). I saw this was an issue for someone else two months back, but don't really know how to solve this.. Any help would be much appreciated! 

Thanks!

**Comment by mmckerns** [comment] 2022-04-19 14:24
I'm not seeing any build errors on any version of the supported python codes, platforms, and dependencies.  What is your OS and version of python? What is your version of mystic and dependencies (e.g. numpy)?

**Comment by mmckerns** [comment] 2022-04-19 14:27
This sounds like it might be a duplicate of #164.

**Comment by DBvdHeijden** [comment] 2022-04-19 14:35
Hi! Thanks for the response - I thought I was running the latest version of python but apparently I was running 2.7 in my conda environment I see now (very dumb haha).. Will try to update to the latest version! Also, thank you for your work on mystic :)

**Comment by DBvdHeijden** [comment] 2022-04-19 15:10
So, I think I was running a newer version of python after all (3.9.7), but the command I used gave the python version the OS itself is running (I think?). I am running macOS Monterey (12.2.1) on a new M1 pro MacBook. My numpy version is 1.22.1 - any tips on what to do?

**Comment by mmckerns** [comment] 2022-04-19 16:02
It sounds like this is a duplicate, as I expected.  This will be fixed with the next released mystic, which should happen in about a week or so.  However, for a first attempt at a workaround, can you can try: `pip install mystic --no-binary :all:`...?

**Comment by mmckerns** [comment] 2022-04-19 16:04
I'm going to close this as a duplicate, but feel free to keep the thread going here until you have resolution.  We can reopen it if it ends up not being a duplicate.

**Closed by mmckerns** 2022-04-19 16:04 UTC
Labels: duplicate
